# Tomcat Configuration
server:
  port: 8003

logging:
  level:
    root: INFO
  file:
    name: application.log
spring:
  application:
    name: simple-app-be
  datasource:
    hikari:
      connection-timeout: 60000 #maximum time in milliseconds to wait for connection
      maximum-pool-size: 10 #pool size = threadNumbers x (connectionPerThread - 1) + 1
      minimumIdle: 4 #minimum number of idle connections maintained in a connection pool
      idleTimeout: 600000 #maximum idle time for connection
      maxLifetime: 1800000 #maximum lifetime in milliseconds of a connection after it is closed
    url: jdbc:postgresql://localhost:3307/simple-db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
