name: Deploy to Elastic Beanstalk

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Extract project name and version from gradle.properties
        id: get_project_info
        run: |
          projectName=$(grep '^projectName=' gradle.properties | cut -d'=' -f2)
          version=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          appName="${projectName}-${version}"
          versionLabel="${version}-${GITHUB_SHA}"
          echo "APP_NAME=$appName" >> $GITHUB_ENV
          echo "VERSION_LABEL=$versionLabel" >> $GITHUB_ENV
      - name: build with gradlew
        run: ./gradlew clean build
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: jar-artifact
          path: simple-app/build/libs/${{ env.APP_NAME }}.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: jar-artifact
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ vars.AWS_APPLICATION_NAME }}
          environment_name: ${{ vars.AWS_ENVIRONMENT_NAME }}
          version_label: ${{ env.VERSION_LABEL }}
          region: ${{ vars.AWS_REGION }}
          deployment_package: ${{ env.APP_NAME }}.jar
